import Booking from "../models/Booking.js"; import Payment from "../models/Payment.js"; import Vendor from "../models/Vendor.js"; import ApiError from "../utils/ApiError.js"; import asyncHandler from "../utils/asyncHandler.js"; import { validateObjectId } from "../utils/validation.js"; import { createPaymentOrder, paymentView, verifyPayment } from "../services/payments/paymentService.js"; import { streamInvoice } from "../services/payments/invoiceService.js";

const cleanPayment = (p) => ({ id: p._id, booking: p.booking, provider: p.provider, currency: p.currency, installmentType: p.installmentType, amount: p.amount, refundedAmount: p.refundedAmount, netAmount: p.netAmount, status: p.status, paymentMethod: p.paymentMethod, transactionId: p.transactionId, failureCode: p.failureCode, failureReason: p.failureReason, invoiceNumber: p.invoiceNumber, paidAt: p.paidAt, refundedAt: p.refundedAt, createdAt: p.createdAt });
export const createOrder = asyncHandler(async (req, res) => { validateObjectId(req.params.bookingId, "booking id"); const allowed = ["booking_deposit", "event_day_payment", "final_payment"]; if (!allowed.includes(req.body.installmentType)) throw new ApiError(400, "A valid installmentType is required."); const result = await createPaymentOrder({ bookingId: req.params.bookingId, installmentType: req.body.installmentType, user: req.user }); res.status(201).json({ success: true, keyId: result.keyId, order: result.order, payment: cleanPayment(result.payment) }); });
export const verify = asyncHandler(async (req, res) => { for (const key of ["razorpay_order_id", "razorpay_payment_id", "razorpay_signature"]) if (!req.body[key]) throw new ApiError(400, `${key} is required.`); const payment = await verifyPayment({ bookingId: req.params.bookingId, user: req.user, body: req.body }); res.json({ success: true, message: payment.status === "captured" ? "Payment confirmed." : "Payment authorized and awaiting provider confirmation.", payment: cleanPayment(payment) }); });
export const getBookingPayments = asyncHandler(async (req, res) => { const booking = await Booking.findById(req.params.bookingId); if (!booking) throw new ApiError(404, "Booking not found."); const vendor = await Vendor.findById(booking.vendorId); const allowed = String(booking.customerId) === String(req.user._id) || String(vendor?.userId) === String(req.user._id) || req.user.role === "admin"; if (!allowed) throw new ApiError(403, "You cannot view these payments."); res.json({ success: true, ...(await paymentView(booking, req.user)) }); });
export const myHistory = asyncHandler(async (req, res) => { const payments = await Payment.find({ customer: req.user._id }).sort({ createdAt: -1 }); res.json({ success: true, payments: payments.map(cleanPayment) }); });
export const getPayment = asyncHandler(async (req, res) => { const payment = await Payment.findById(req.params.paymentId); if (!payment) throw new ApiError(404, "Payment not found."); const vendor = await Vendor.findById(payment.vendor); if (String(payment.customer) !== String(req.user._id) && String(vendor?.userId) !== String(req.user._id) && req.user.role !== "admin") throw new ApiError(403, "You cannot view this payment."); res.json({ success: true, payment: cleanPayment(payment) }); });
export const invoice = asyncHandler(async (req, res) => { const payment = await Payment.findById(req.params.paymentId); if (!payment || !["captured", "partially_refunded", "refunded"].includes(payment.status)) throw new ApiError(404, "Invoice is not available."); const booking = await Booking.findById(payment.booking).populate("customerId", "name email").populate("vendorId", "businessName userId"); const allowed = String(booking.customerId._id) === String(req.user._id) || req.user.role === "admin" || (req.user.role === "vendor" && String(booking.vendorId.userId) === String(req.user._id)); if (!allowed) throw new ApiError(403, "You cannot access this invoice."); await streamInvoice({ payment, booking, customer: booking.customerId, vendor: booking.vendorId, res }); });
